List<Map<String, String>> videoPostdata = [
  {
    "userName": "john_doe",
    "like": "11.2K",
    "comment": "1.5k",
    "share": "30",
    "caption": "Enjoying the sunset 🌅",
    "video": "assets/videos/video1.mp4",
    "profileUser":"https://tse4.mm.bing.net/th?id=OIP.cEie_pmgXcu1Blpul3mrfgHaFj&pid=Api&P=0&h=220"
  },
  {
    "userName": "emma_rose",
    "like": "9.8k",
    "comment": "1.2k",
    "share": "25",
    "caption": "Morning vibes ☕",
    "video": "assets/videos/video2.mp4",
    "profileUser":"https://tse2.mm.bing.net/th?id=OIP.MNYMRopweKA9axhd73z_GwHaE8&pid=Api&P=0&h=220"
  },
  {
    "userName": "alex_king",
    "like": "32.3K",
    "comment": "8k",
    "share": "245",
    "caption": "Adventure time 🏞️",
    "video": "assets/videos/video3.mp4",
    "profileUser":"https://tse1.mm.bing.net/th?id=OIP.FZsskT3BF6cUQ93s_I1BtQAAAA&pid=Api&P=0&h=220"
  },
  {
    "userName": "sophia_m",
    "like": "12.8K",
    "comment": "2.5k",
    "share": "1k",
    "caption": "Workout goals 💪",
    "video": "assets/videos/video4.mp4",
    "profileUser":"https://tse4.mm.bing.net/th?id=OIP.5eJS8vMUhr7TzxzdbAX3GQHaJP&pid=Api&P=0&h=220"
  },
  {
    "userName": "mike_b",
    "like": "33K",
    "comment": "4.8k",
    "share": "2.6k",
    "caption": "Epic road trip 🚗",
    "video": "assets/videos/video5.mp4",
    "profileUser":"https://tse3.mm.bing.net/th?id=OIP.v2btc1HcWm37V1Mt8vkaTgHaHa&pid=Api&P=0&h=220"
  },
  {
    "userName": "lucas_w",
    "like": "28.1K",
    "comment": "3k",
    "share": "1.8k",
    "caption": "Chill beats 🎶",
    "video": "assets/videos/video6.mp4",
    "profileUser":"https://tse2.mm.bing.net/th?id=OIP.pSWEV7NEYkBoAEJ_Ae4D9QHaHa&pid=Api&P=0&h=220"
  },
  {
    "userName": "olivia_c",
    "like": "43.5K",
    "comment": "5.3k",
    "share": "2.9k",
    "caption": "Fresh blooms 🌸",
    "video": "assets/videos/video7.mp4",
    "profileUser":"https://tse2.mm.bing.net/th?id=OIP.iGXsP6uTRHkzK4AjvwghOwHaJ3&pid=Api&P=0&h=220"
  },
  {
    "userName": "daniel_j",
    "like": "43K",
    "comment": "5.1k",
    "share": "2.2k",
    "caption": "Skate life 🛹",
    "video": "assets/videos/video8.mp4",
    "profileUser":"https://tse3.mm.bing.net/th?id=OIP.VZ9ba9AeIiJ7lPLR8C2fjwHaHa&pid=Api&P=0&h=220"
  },
  {
    "userName": "ava_l",
    "like": "19.9K",
    "comment": "1.1k",
    "share": "550",
    "caption": "Ocean breeze 🌊",
    "video": "assets/videos/video9.mp4",
    "profileUser":"https://tse3.mm.bing.net/th?id=OIP.PztowP3ljup0SM75tkDimQHaHa&pid=Api&P=0&h=220"
  },
  {
    "userName": "liam_r",
    "like": "32.4K",
    "comment": "2.2k",
    "share": "300",
    "caption": "Foodie heaven 🍕",
    "video": "assets/videos/video10.mp4",
    "profileUser":"https://tse1.mm.bing.net/th?id=OIP.OgRB0U7cw81ZoY9UyZVWvAHaHa&pid=Api&P=0&h=220"
  },
  {
    "userName": "chloe_s",
    "like": "16.1K",
    "comment": "2.2k",
    "share": "350",
    "caption": "City lights 🌃",
    "video": "assets/videos/video11.mp4",
    "profileUser":"https://tse2.mm.bing.net/th?id=OIP.chdPqeJIIzQx08qzKtR5uwHaGl&pid=Api&P=0&h=220",
  },
  {
    "userName": "jack_t",
    "like": "24.7K",
    "comment": "2.2k",
    "share": "1.1k",
    "caption": "Mountain views ⛰️",
    "video": "assets/videos/video12.mp4",
    "profileUser":"https://tse1.mm.bing.net/th?id=OIP.o-g05PnmghSpqF9THnv5aQHaHY&pid=Api&P=0&h=220",
  },
  {
    "userName": "mia_g",
    "like": "10.3K",
    "comment": "1k",
    "share": "459",
    "caption": "Lazy Sundays ☀️",
    "video": "assets/videos/video13.mp4",
    "profileUser":"https://tse1.mm.bing.net/th?id=OIP.T0FxGkSePOI-Pzth1yEOYQHaGK&pid=Api&P=0&h=220",
  },
  {
    "userName": "noah_h",
    "like": "26.9K",
    "comment": "3.3k",
    "share": "1k",
    "caption": "Concert vibes 🎤",
    "video": "assets/videos/video14.mp4",
    "profileUser":"https://tse3.mm.bing.net/th?id=OIP.a1wZFgHBcKDqm_vzWixHXAHaJQ&pid=Api&P=0&h=220",
  },
  {
    "userName": "isabella_k",
    "like": "52.5K",
    "comment": "10k",
    "share": "3.4k",
    "caption": "Nature walk 🍃",
    "video": "assets/videos/video15.mp4",
    "profileUser":"https://tse2.mm.bing.net/th?id=OIP.CmJv6yQreCDahpZ0jyUzMgHaHa&pid=Api&P=0&h=220",
  },
  {
    "userName": "ethan_m",
    "like": "34.1K",
    "comment": "3.2k",
    "share": "2.1k",
    "caption": "Game night 🎮",
    "video": "assets/videos/video16.mp4",
    "profileUser":"https://tse4.mm.bing.net/th?id=OIP.IGNf7GuQaCqz_RPq5wCkPgHaLH&pid=Api&P=0&h=220",
  },
  {
    "userName": "amelia_p",
    "like": "21.7K",
    "comment": "1.4k",
    "share": "500",
    "caption": "Book lover 📚",
    "video": "assets/videos/video17.mp4",
    "profileUser":"https://tse3.mm.bing.net/th?id=OIP.DN_P32n3WLFqwbfYsml3zgHaHR&pid=Api&P=0&h=220",
  },
  {
    "userName": "logan_q",
    "like": "12.2K",
    "comment": "1.2k",
    "share": "211",
    "caption": "Car showcase 🚘",
    "video": "assets/videos/video18.mp4",
    "profileUser":"https://tse2.mm.bing.net/th?id=OIP.kf9TvsuxepBOhAV4cTHEoAHaHa&pid=Api&P=0&h=220",
  },
  {
    "userName": "ella_r",
    "like": "44.4K",
    "comment": "5.3k",
    "share": "2.2k",
    "caption": "Baking fun 🍰",
    "video": "assets/videos/video19.mp4",
    "profileUser":"https://tse2.mm.bing.net/th?id=OIP.gxCrcJ9wcnuS-hppF4l8ggHaHa&pid=Api&P=0&h=220",
  },
  {
    "userName": "william_s",
    "like": "35.8K",
    "comment": "2.1k",
    "share": "515",
    "caption": "Beach party 🏖️",
    "video": "assets/videos/video20.mp4",
    "profileUser":"https://tse1.mm.bing.net/th?id=OIP.xAT_cGKFbfl-DMc-uKGJIgHaHa&pid=Api&P=0&h=220",
  },
];
